name: Bluesky Labeler
on:
  push:
    branches: [main]
  schedule:
    - cron: '*/15 * * * *' # Läuft alle 15 Minuten, um Haken aktuell zu halten

jobs:
  label:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Cache labels database
        uses: actions/cache@v4
        with:
          path: labels.db
          key: labels-db-${{ github.ref_name }}
          restore-keys: labels-db-
      - run: bun install
      - run: bun run start
        env:
          DID: ${{ secrets.DID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
